const ENV_ALIASES = [
  ['SIGNAL_DATA_DIR', 'RADAR_DATA_DIR'],
  ['SIGNAL_FILE_LOG_ENABLED', 'RADAR_FILE_LOG_ENABLED'],
  ['SIGNAL_SCAN_INTERVAL', 'RADAR_SCAN_INTERVAL'],
  ['SIGNAL_SCAN_ROW_LIMIT', 'RADAR_TELEGRAM_ROW_LIMIT'],
  ['SIGNAL_HTTP_PROXY_MODE', 'RADAR_HTTP_PROXY_MODE'],
  ['SIGNAL_HTTP_PROXY_URL', 'RADAR_HTTP_PROXY_URL'],
  ['SIGNAL_STORAGE_DRIVER', 'RADAR_STORAGE_DRIVER'],
  ['SIGNAL_DB_DRIVER', 'RADAR_DB_DRIVER'],
  ['SIGNAL_DATABASE_URL', 'RADAR_DATABASE_URL'],
  ['SIGNAL_SQLITE_PATH', 'RADAR_SQLITE_PATH'],
  ['SIGNAL_MAX_MC', 'RADAR_MAX_MC'],
  ['SIGNAL_MIN_MC', 'RADAR_MIN_MC'],
  ['SIGNAL_MIN_LIQUIDITY', 'RADAR_MIN_LIQUIDITY'],
  ['SIGNAL_PUSH_MIN_LIQUIDITY', 'RADAR_PUSH_MIN_LIQUIDITY'],
  ['SIGNAL_PUSH_MIN_HOLDERS', 'RADAR_PUSH_MIN_HOLDERS'],
  ['SIGNAL_PUSH_MIN_VOLUME', 'RADAR_PUSH_MIN_VOLUME'],
  ['SIGNAL_PUSH_MIN_BUY_SELL_RATIO', 'RADAR_PUSH_MIN_BUY_SELL_RATIO'],
  ['SIGNAL_REQUIRE_SOCIALS', 'RADAR_REQUIRE_SOCIALS'],
  ['SIGNAL_MIN_SMART_DEGEN', 'RADAR_MIN_SMART_DEGEN'],
  ['SIGNAL_TRADE_SCORE_THRESHOLD', 'RADAR_TRADE_SCORE_THRESHOLD'],
  ['SIGNAL_TRADE_MIN_SMART_MONEY', 'RADAR_TRADE_MIN_SMART_MONEY'],
  ['SIGNAL_TRADE_MAX_SIGNAL_COUNT', 'RADAR_TRADE_MAX_SIGNAL_COUNT'],
  ['SIGNAL_TRADE_MIN_LIQUIDITY', 'RADAR_TRADE_MIN_LIQUIDITY'],
  ['SIGNAL_TRADE_MIN_VOLUME', 'RADAR_TRADE_MIN_VOLUME'],
  ['SIGNAL_TRADE_MIN_BUY_SELL_RATIO', 'RADAR_TRADE_MIN_BUY_SELL_RATIO'],
  ['SIGNAL_PAPER_TP_PERCENT', 'RADAR_PAPER_TP_PERCENT'],
  ['SIGNAL_PAPER_SL_PERCENT', 'RADAR_PAPER_SL_PERCENT'],
  ['SIGNAL_PAPER_TP_STEPS', 'RADAR_PAPER_TP_STEPS'],
  ['SIGNAL_PAPER_TP1_PERCENT', 'RADAR_PAPER_TP1_PERCENT'],
  ['SIGNAL_PAPER_TP1_SELL_PERCENT', 'RADAR_PAPER_TP1_SELL_PERCENT'],
  ['SIGNAL_PAPER_TP2_PERCENT', 'RADAR_PAPER_TP2_PERCENT'],
  ['SIGNAL_PAPER_TP2_SELL_PERCENT', 'RADAR_PAPER_TP2_SELL_PERCENT'],
  ['SIGNAL_PAPER_TP3_PERCENT', 'RADAR_PAPER_TP3_PERCENT'],
  ['SIGNAL_PAPER_TP3_SELL_PERCENT', 'RADAR_PAPER_TP3_SELL_PERCENT'],
  ['SIGNAL_PAPER_BASE_POSITION_USD', 'RADAR_PAPER_BASE_POSITION_USD'],
  ['SIGNAL_PAPER_TOTAL_CAPITAL_USD', 'RADAR_PAPER_TOTAL_CAPITAL_USD'],
  ['SIGNAL_PAPER_MAX_OPEN_POSITIONS', 'RADAR_PAPER_MAX_OPEN_POSITIONS'],
  ['SIGNAL_PAPER_MAX_CAPITAL_USAGE_PCT', 'RADAR_PAPER_MAX_CAPITAL_USAGE_PCT'],
  ['SIGNAL_DATA_RETENTION_DAYS', 'RADAR_DATA_RETENTION_DAYS'],
  ['SIGNAL_TG_TIMEOUT_MS', 'RADAR_TG_TIMEOUT_MS'],
  ['SIGNAL_TG_MAX_RETRIES', 'RADAR_TG_MAX_RETRIES'],
  ['SIGNAL_TG_RETRY_DELAY_MS', 'RADAR_TG_RETRY_DELAY_MS'],
  ['SIGNAL_PAPER_TIME_STOP_HOURS', 'RADAR_PAPER_TIME_STOP_HOURS'],
  ['SIGNAL_PAPER_TRAILING_START_PERCENT', 'RADAR_PAPER_TRAILING_START_PERCENT'],
  ['SIGNAL_PAPER_TRAILING_STOP_PERCENT', 'RADAR_PAPER_TRAILING_STOP_PERCENT'],
];

for (const [signalKey, legacyKey] of ENV_ALIASES) {
  const signalValue = process.env[signalKey];
  if (
    (process.env[legacyKey] == null || process.env[legacyKey] === '') &&
    signalValue != null &&
    signalValue !== ''
  ) {
    process.env[legacyKey] = signalValue;
  }
}
